
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      FITBIT_CLIENT_ID: ${FITBIT_CLIENT_ID}
      FITBIT_CLIENT_SECRET: ${FITBIT_CLIENT_SECRET}
      FITBIT_REDIRECT_URI: http://127.0.0.1:5001/callback
      FRONTEND_URL: http://127.0.0.1:3000
      OAUTHLIB_INSECURE_TRANSPORT: 1
    volumes:
      - .:/app
    # Use the virtual environment's python to run the app
    command: python app.py

  frontend:
    build:
      context: .
      dockerfile: dashboard/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_API_URL: http://backend:5001
    depends_on:
      - backend